name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # at every Friday 5:30
    - cron: "30 17 * * 5"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: -c lychee.toml content
          output: ./lychee/out.md
          # Don't fail action on broken links
          fail: false

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
